-- HelpDesk Live - Supabase schema
-- Run this whole file in Supabase > SQL Editor once.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  department text,
  role text not null default 'user' check (role in ('user','it','admin')),
  created_at timestamptz not null default now()
);

create sequence if not exists public.ticket_number_seq start 1;

create table if not exists public.tickets (
  id bigint generated by default as identity primary key,
  ticket_number text unique,
  requester_id uuid not null references public.profiles(id),
  category text not null,
  title text not null check (char_length(title) between 3 and 140),
  description text not null,
  priority text not null default 'normal' check (priority in ('low','normal','high','critical')),
  status text not null default 'new' check (status in ('new','accepted','in_progress','waiting_user','closed')),
  assigned_to uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  accepted_at timestamptz,
  closed_at timestamptz,
  resolution text
);

create table if not exists public.ticket_logs (
  id bigint generated by default as identity primary key,
  ticket_id bigint not null references public.tickets(id) on delete cascade,
  action text not null,
  actor_id uuid references public.profiles(id),
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists tickets_requester_idx on public.tickets(requester_id);
create index if not exists tickets_status_idx on public.tickets(status);
create index if not exists tickets_created_idx on public.tickets(created_at desc);
create index if not exists ticket_logs_ticket_idx on public.ticket_logs(ticket_id, created_at);

-- Create profile automatically when a new Auth user is created.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name, department)
  values (
    new.id,
    new.email,
    nullif(new.raw_user_meta_data->>'full_name', ''),
    nullif(new.raw_user_meta_data->>'department', '')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Generate human-readable ticket number from a server-side sequence.
create or replace function public.set_ticket_number()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  n bigint;
begin
  if new.ticket_number is null then
    n := nextval('public.ticket_number_seq');
    new.ticket_number := 'IT-' || to_char(now() at time zone 'Asia/Bangkok', 'YYYY') || '-' || lpad(n::text, 5, '0');
  end if;
  return new;
end;
$$;

drop trigger if exists before_ticket_insert on public.tickets;
create trigger before_ticket_insert
before insert on public.tickets
for each row execute procedure public.set_ticket_number();

-- Security helper. SECURITY DEFINER avoids recursive RLS checks.
create or replace function public.is_it_staff(p_user uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = p_user and role in ('it','admin')
  );
$$;

grant execute on function public.is_it_staff(uuid) to authenticated;

alter table public.profiles enable row level security;
alter table public.tickets enable row level security;
alter table public.ticket_logs enable row level security;

drop policy if exists "profiles read own or staff" on public.profiles;
create policy "profiles read own or staff"
on public.profiles for select
to authenticated
using (id = auth.uid() or public.is_it_staff(auth.uid()));

drop policy if exists "tickets users create own" on public.tickets;
create policy "tickets users create own"
on public.tickets for insert
to authenticated
with check (requester_id = auth.uid());

drop policy if exists "tickets users read own or staff" on public.tickets;
create policy "tickets users read own or staff"
on public.tickets for select
to authenticated
using (requester_id = auth.uid() or public.is_it_staff(auth.uid()));

drop policy if exists "ticket logs read own or staff" on public.ticket_logs;
create policy "ticket logs read own or staff"
on public.ticket_logs for select
to authenticated
using (
  exists (
    select 1 from public.tickets t
    where t.id = ticket_id
      and (t.requester_id = auth.uid() or public.is_it_staff(auth.uid()))
  )
);

-- Staff-only server functions: timestamps come from the database, not the browser.
create or replace function public.accept_ticket(p_ticket_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_it_staff(auth.uid()) then
    raise exception 'Not authorized';
  end if;

  update public.tickets
  set
    status = case when status = 'new' then 'accepted' else status end,
    assigned_to = coalesce(assigned_to, auth.uid()),
    accepted_at = coalesce(accepted_at, now())
  where id = p_ticket_id
    and status <> 'closed';

  if not found then raise exception 'Ticket not found or already closed'; end if;

  insert into public.ticket_logs(ticket_id, action, actor_id)
  values (p_ticket_id, 'accepted', auth.uid());
end;
$$;

create or replace function public.set_ticket_status(p_ticket_id bigint, p_status text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_it_staff(auth.uid()) then
    raise exception 'Not authorized';
  end if;

  if p_status not in ('in_progress','waiting_user') then
    raise exception 'Invalid status';
  end if;

  update public.tickets
  set
    status = p_status,
    assigned_to = coalesce(assigned_to, auth.uid()),
    accepted_at = coalesce(accepted_at, now())
  where id = p_ticket_id and status <> 'closed';

  if not found then raise exception 'Ticket not found or already closed'; end if;

  insert into public.ticket_logs(ticket_id, action, actor_id, details)
  values (p_ticket_id, 'status_changed', auth.uid(), jsonb_build_object('status', p_status));
end;
$$;

create or replace function public.close_ticket(p_ticket_id bigint, p_resolution text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_it_staff(auth.uid()) then
    raise exception 'Not authorized';
  end if;

  if nullif(trim(p_resolution), '') is null then
    raise exception 'Resolution is required';
  end if;

  update public.tickets
  set
    status = 'closed',
    assigned_to = coalesce(assigned_to, auth.uid()),
    accepted_at = coalesce(accepted_at, now()),
    closed_at = now(),
    resolution = trim(p_resolution)
  where id = p_ticket_id and status <> 'closed';

  if not found then raise exception 'Ticket not found or already closed'; end if;

  insert into public.ticket_logs(ticket_id, action, actor_id, details)
  values (p_ticket_id, 'closed', auth.uid(), jsonb_build_object('resolution', trim(p_resolution)));
end;
$$;

revoke all on function public.accept_ticket(bigint) from public;
revoke all on function public.set_ticket_status(bigint,text) from public;
revoke all on function public.close_ticket(bigint,text) from public;
grant execute on function public.accept_ticket(bigint) to authenticated;
grant execute on function public.set_ticket_status(bigint,text) to authenticated;
grant execute on function public.close_ticket(bigint,text) to authenticated;

-- Realtime: add tickets to the Supabase realtime publication if not already added.
do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'tickets'
  ) then
    alter publication supabase_realtime add table public.tickets;
  end if;
end $$;

-- Optional: Realtime for ticket timeline logs as well.
do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'ticket_logs'
  ) then
    alter publication supabase_realtime add table public.ticket_logs;
  end if;
end $$;
